using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace kinatraa.AudioSystem.Editor
{
    /// <summary>Generates a static class of <c>const string</c> cue and playlist ids. Output is sorted, so it is deterministic.</summary>
    internal static class AudioIdsGenerator
    {
        private const string DefaultPath = "Assets/Scripts/Generated/AudioIds.cs";

        [MenuItem(AudioEditorUtility.MenuRoot + "Generate Audio Ids", false, 20)]
        internal static void GenerateAndReport()
        {
            string path = Generate();
            if (path == null) return;
            Debug.Log("[kinatraa Audio] Audio ids written to " + path);
            EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path));
        }

        /// <summary>Writes the ids file if its content changed. Returns the asset path, or null on error.</summary>
        internal static string Generate()
        {
            AudioEditorUtility.Invalidate();
            AudioSystemConfig config = AudioEditorUtility.FindConfig();
            string path = config != null && !string.IsNullOrEmpty(config.idsOutputPath) ? config.idsOutputPath : DefaultPath;
            string className = config != null && !string.IsNullOrEmpty(config.idsClassName) ? config.idsClassName : "AudioIds";
            string ns = config != null ? config.idsNamespace : "";
            if (!path.StartsWith("Assets/", StringComparison.Ordinal) || !path.EndsWith(".cs", StringComparison.Ordinal))
            {
                Debug.LogError("[kinatraa Audio] Ids output path must start with 'Assets/' and end with '.cs': " + path);
                return null;
            }

            var cueIds = new SortedSet<string>(StringComparer.Ordinal);
            var playlistIds = new SortedSet<string>(StringComparer.Ordinal);
            foreach (AudioLibrary lib in AudioEditorUtility.Libraries)
            {
                foreach (AudioCue cue in lib.cues)
                {
                    if (cue != null && !string.IsNullOrEmpty(cue.id)) cueIds.Add(cue.id);
                }
                foreach (AudioPlaylist list in lib.playlists)
                {
                    if (list != null && !string.IsNullOrEmpty(list.id)) playlistIds.Add(list.id);
                }
            }

            string source = BuildSource(cueIds, playlistIds, className, ns);
            string fullPath = Path.GetFullPath(path);
            if (File.Exists(fullPath) && File.ReadAllText(fullPath) == source) return path;
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
            File.WriteAllText(fullPath, source);
            AssetDatabase.ImportAsset(path);
            return path;
        }

        internal static string BuildSource(IEnumerable<string> cueIds, IEnumerable<string> playlistIds, string className, string ns)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("// Generated by kinatraa Audio System (").Append(AudioEditorUtility.MenuRoot).Append("Generate Audio Ids).\n");
            sb.Append("// Do not edit by hand: changes are overwritten on the next generation.\n");
            sb.Append("// </auto-generated>\n");
            sb.Append("#pragma warning disable 1591\n\n");
            string indent = "";
            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").Append(ns).Append("\n{\n");
                indent = "    ";
            }
            sb.Append(indent).Append("/// <summary>Audio cue ids. Use with kinatraa.AudioSystem.Audio.Play.</summary>\n");
            sb.Append(indent).Append("public static class ").Append(className).Append("\n");
            sb.Append(indent).Append("{\n");
            AppendConstants(sb, indent + "    ", cueIds, new HashSet<string> { className, "Playlists" });

            sb.Append("\n").Append(indent).Append("    /// <summary>Playlist ids. Use with kinatraa.AudioSystem.Audio.PlayPlaylist.</summary>\n");
            sb.Append(indent).Append("    public static class Playlists\n");
            sb.Append(indent).Append("    {\n");
            AppendConstants(sb, indent + "        ", playlistIds, new HashSet<string> { className, "Playlists" });
            sb.Append(indent).Append("    }\n");
            sb.Append(indent).Append("}\n");
            if (!string.IsNullOrEmpty(ns)) sb.Append("}\n");
            return sb.ToString();
        }

        private static void AppendConstants(StringBuilder sb, string indent, IEnumerable<string> ids, HashSet<string> used)
        {
            foreach (string id in ids)
            {
                string name = AudioEditorUtility.ToIdentifier(id);
                string unique = name;
                for (int n = 2; !used.Add(unique); n++) unique = name + n;
                sb.Append(indent).Append("public const string ").Append(unique).Append(" = \"")
                    .Append(id.Replace("\\", "\\\\").Replace("\"", "\\\"")).Append("\";\n");
            }
        }
    }
}
